name: Deploy
 
on:
  push:
    branches: [main, "feature/*"]
  pull_request:
    branches: [main, "feature/*"]
 
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
 
    strategy:
      matrix:
        node-version: [19]
 
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
 
      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm install
      #- name: Run Database migrations
        #run: npm run migrate
        #env:
          #DB_HOST: mongodb://mongo:2s0ysB1rDIWJ1hrjEZzh@containers-us-west-56.railway.app:6241
      - name: Run Tests
        run: npm run test:ci
        env:
          DB_HOST: mongodb://mongo:2s0ysB1rDIWJ1hrjEZzh@containers-us-west-56.railway.app:6241
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
      - name: Run Build
        run: npm run build
      - uses: codecov/codecov-action@v3
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
          flags: unittests # optional
          name: codecov-umbrella # optional
      - name: 🐳 Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 🐳 Setup buildx
        uses: docker/setup-buildx-action@v2
      - name: 🐳 Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./infrastructure/Dockerfile
          push: true
          tags: | 
            ghcr.io/maetzl/ice_backend:latest
